apply plugin: 'java'
apply plugin: 'com.palantir.external-publish-intellij'

repositories {
    intellijPlatform {
        defaultRepositories()
    }
}

dependencies {
    intellijPlatform {
        intellijIdeaCommunity('2024.1') {
            useInstaller = false
        }
        bundledPlugins('com.intellij.java', 'org.jetbrains.plugins.gradle')
    }
}

intellijPlatform {
    projectName = 'palantir-gradle-jdks'
    pluginConfiguration {
        description = 'Configures the Gradle JDKs for the Toolchains used for a project and for the Gradle Daemon.'
        ideaVersion {
            sinceBuild = '241' // TODO: test against this version of IntelliJ to ensure no regressions
            untilBuild = provider { null }
        }
    }
    pluginVerification {
        ides {
            create('IC', '2024.1')
        }
    }
}

// Javadoc fails if there are no public classes to javadoc, so make it stop complaining.
tasks.named("javadoc", Javadoc) {
    failOnError = false
}

tasks.withType(JavaCompile).configureEach {
    options.errorprone.disable 'PreferSafeLoggableExceptions'
}

javaVersion {
    target = 17
    runtime = 17
}
